/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
*/

var findTheDifference = function(s, t) {


    let hash = {}
  
    for(element of s){
        if(hash[element] === undefined){
            hash[element] = 1 //if havent encountered element
        } else {
            hash[element] ++ //if already encountered element increment up
        }
    }
    
    for(element of t){
        if(hash[element] != undefined && hash[element] > 0){
            hash[element] --
        } else {
            return element
        }
    }
    return - 1
};





function getDifferentNumber(arr) {
  // your code goes here
  if(!arr) return 0
  
  let n = arr.sort() // n
  for(let i = 0; i < n.length; i++){
    if(n[i] != i){
      return i 
    }
  }
  return arr.length
}





//interviewcake

function getDifferentNumber(arr) {

  let obj = {}
  
  for(element of arr){ //[0,1,2,3]
    obj[element] = true
  }
  
  for(let i = 0; i < arr.length; i++){
    if(!obj.hasOwnProperty(i)){
      return i
    }
  }
  return arr.length
}

